2019-04-14 08:59:39,412 - Logs.Loggers - WARNING - WARN: ERROR AT FOLLOWING POINT  - [in /Users/nishantmakkar/PycharmProjects/Day1/Logs/run_logs.py:3]
2019-04-14 09:00:50,358 - Logs.Loggers - WARNING - WARN: ERROR AT FOLLOWING POINT  - [in /Users/nishantmakkar/PycharmProjects/Day1/Logs/run_logs.py:8]
2019-04-14 09:00:52,572 - Logs.Loggers - WARNING - WARN: ERROR AT FOLLOWING POINT  - [in /Users/nishantmakkar/PycharmProjects/Day1/Logs/run_logs.py:8]
